Prisma schema + initial migration (based on previously created ERD)
hyter99/AI_22-23_L1 pull request #25
Opened 2022-10-20 17:52 UTC by marcin98b

2022-10-20 18:01 UTC, Gabryjiel requested changes

2022-10-20 18:01 UTC, Gabryjiel commented on prisma/schema.prisma
> +  price             Decimal             @db.Decimal(16, 2)
Price should be integer. Currency should be stored in db in cents or parts of cents.

2022-10-20 18:01 UTC, Gabryjiel commented on prisma/schema.prisma
> +  buyOffer_id    Int           @id
Pick one case: camelCase or pascal_case. Camel case is preferred in JavaScript world.

2022-10-20 18:01 UTC, Gabryjiel commented on prisma/schema.prisma
> +  user_transaction_buyer_idTouser  user      @relation("transaction_buyer_idTouser", fields: [buyer_id], references: [user_id], onDelete: Cascade, map: "buyer")
Can these long names be shortened?

2022-10-20 18:01 UTC, Gabryjiel commented on prisma/schema.prisma
> +model buyOffer {
Modele dużą literą będą lepiej wyglądały.

2022-10-20 18:04 UTC, Gabryjiel commented
Change target branch into 'develop' not 'main'.

Feature branches should be merged into develop then develop is merged into main.

2022-10-20 20:28 UTC, marcin98b commented on prisma/schema.prisma
> +  buyOffer_id    Int           @id
Fixed naming convention in latest commit

2022-10-20 20:29 UTC, marcin98b commented on prisma/schema.prisma
> +  user_transaction_buyer_idTouser  user      @relation("transaction_buyer_idTouser", fields: [buyer_id], references: [user_id], onDelete: Cascade, map: "buyer")
Fixed relationship naming convention in latest commit

2022-10-20 20:47 UTC, marcin98b commented on prisma/schema.prisma
> +  price             Decimal             @db.Decimal(16, 2)
Splitted price field into two as suggested
https://github.com/hyter99/AI_22-23_L1/commit/765902511bc6c7687944cc32af4aaa97f86bacb2

2022-10-20 20:48 UTC, Gabryjiel commented on prisma/schema.prisma
> +  price             Decimal             @db.Decimal(16, 2)
No no, I suggested single Integer field.

Instead of 1,50 dollar I would say it's better to store 150 cents.

2022-10-20 20:58 UTC, marcin98b commented on prisma/schema.prisma
> +  price             Decimal             @db.Decimal(16, 2)
sure, np
https://github.com/hyter99/AI_22-23_L1/pull/25/commits/267b7b85310518f938d53990b50f23ddeb7acbd2

2022-10-21 10:03 UTC, BartoszGrz approved these changes

2022-10-24 15:53 UTC, closed without merging